package io.github.edadma.texish.parser

import org.scalatest.freespec.AnyFreeSpec
import org.scalatest.matchers.should.Matchers

/** The USFM → texish translation. `Usfm.translate` is a pure function, so these pin the exact rewriting of every
  * marker class the `usfm` package styles — independent of any typesetter, on every backend.
  */
class UsfmTranslateTests extends AnyFreeSpec with Matchers:

  private def tr(s: String): String = Usfm.translate(s)

  "a paragraph marker starts a body macro and its text flows after it" in {
    tr("\\p \\v 1 In the beginning.") shouldBe "\\usfmp{1}\\usfmv{1}In the beginning."
  }

  "a chapter number is split from the text that follows" in {
    tr("\\c 1\n\\p \\v 1 Text") shouldBe "\\usfmc{1}\\usfmp{1}\\usfmv{1}Text"
  }

  "a verse number is split from the text and the remainder flows on" in {
    tr("\\v 2 He was with God.") shouldBe "\\usfmv{2}He was with God."
  }

  "a poetry marker carries its level, a second line its own" in {
    tr("\\q1 \\v 1 Blessed\n\\q2 who walks") shouldBe "\\usfmq{1}\\usfmv{1}Blessed \\usfmq{2}who walks"
  }

  "a stanza break becomes \\usfmb with no argument" in {
    tr("\\q1 line\n\\b\n\\q1 next") shouldBe "\\usfmq{1}line \\usfmb \\usfmq{1}next"
  }

  "a section heading captures its content up to the next block marker" in {
    tr("\\s1 The Beginning\n\\p \\v 1 Text") shouldBe
      "\\usfms{1}{The Beginning }\\usfmp{1}\\usfmv{1}Text"
  }

  "a heading marker without a level defaults it to 1" in {
    tr("\\d A Psalm of David\n\\q1 O LORD") shouldBe
      "\\usfmd{1}{A Psalm of David }\\usfmq{1}O LORD"
  }

  "a descriptive title keeps an embedded verse number inside its argument" in {
    tr("\\d \\v 1 A Psalm of David.\n\\q1 O LORD") shouldBe
      "\\usfmd{1}{\\usfmv{1}A Psalm of David. }\\usfmq{1}O LORD"
  }

  "a words-of-Jesus span is wrapped and closed" in {
    tr("\\p \\wj Follow Me.\\wj* Now") shouldBe "\\usfmp{1}\\usfmwj{Follow Me.} Now"
  }

  "a cross-reference splits display text from its canonical target" in {
    tr("\\r (\\ref Genesis 1:1|GEN 1:1\\ref*)") shouldBe
      "\\usfmr{1}{(\\usfmref{Genesis 1:1}{GEN 1:1})}"
  }

  "a reference with no pipe uses the display text as the target too" in {
    tr("\\r \\ref John 1:1\\ref*") shouldBe "\\usfmr{1}{\\usfmref{John 1:1}{John 1:1}}"
  }

  "a footnote becomes nested segment macros, its caller dropped" in {
    tr("\\p \\v 5 overcome\\f + \\fr 1:5 \\ft Or \\fqa comprehended\\f* it.") shouldBe
      "\\usfmp{1}\\usfmv{5}overcome\\usfmfootnote{\\usfmfr{1:5 }\\usfmft{Or }\\usfmfqa{comprehended}} it."
  }

  "a footnote segment carries an embedded cross-reference" in {
    tr("\\p text\\f + \\ft see \\ref Acts 4:25|ACT 4:25\\ref*\\f*") shouldBe
      "\\usfmp{1}text\\usfmfootnote{\\usfmft{see \\usfmref{Acts 4:25}{ACT 4:25}}}"
  }

  "a verse number inside a footnote stays within its text segment" in {
    tr("\\p a\\f + \\ft x \\fv 4\\fv*y\\f*") shouldBe
      "\\usfmp{1}a\\usfmfootnote{\\usfmft{x \\usfmfv{4}y}}"
  }

  "metadata markers and their lines are dropped" in {
    tr("\\id JHN Autogenerated\n\\usfm 3.1\n\\p body") shouldBe "\\usfmp{1}body"
  }

  "characters special to texish are escaped in running text" in {
    tr("\\p a{b}~c $x") shouldBe "\\usfmp{1}a\\{b\\}\\~c \\$x"
  }

  "a doubled slash in text is broken so it is not read as a comment" in {
    tr("\\p and/or a//b") shouldBe "\\usfmp{1}and/or a/{}/b"
  }

  "an unrecognised character marker keeps its text but drops the styling" in {
    tr("\\p a \\xyz kept\\xyz* b") shouldBe "\\usfmp{1}a kept b"
  }
